{{- range $key, $api := .Values.apis }}
{{- if $api.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $api.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
        rate(
          istio_requests_total{
            destination_workload="{{ $api.name }}",
            destination_workload_namespace="{{ $.Release.Namespace }}"
          }[1m]
        )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="{{ $.Release.Namespace }}",
            pod_name=~"{{ $api.name }}.*"
          }
        ) by (pod_name)
      )
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $api.name }}
  metrics:
    - type: Object
      object:
        metricName: istio-requests-total
        target:
          apiVersion: v1
          kind: Pod
          name: {{ $api.name }}
        targetValue: 10
---
{{- end }}
{{- end }}