{{- range $key, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
      - name: {{ $key }}
        {{- if $.Values.registry }}
        image: {{ $.Values.registry }}/{{ $key }}:{{ $api.version }}
        {{- else }}
        image: {{ $key }}:{{ $api.version }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        resources:
          limits:
            cpu: {{ $api.resourcesLimitsCpu | default ($.Values.resourcesLimitsCpu | default "500m") }}
            memory: {{ $api.resourcesLimitsMemory | default ($.Values.resourcesLimitsMemory | default "512Mi") }}
          requests:
            cpu: {{ $api.resourcesRequestsCpu | default ($.Values.resourcesRequestsCpu | default "50m") }}
            memory: {{ $api.resourcesRequestsMemory | default ($.Values.resourcesRequestsMemory | default "128Mi") }}
        ports:
        - containerPort: {{ $api.port }}
          name: user-port
          protocol: TCP
        env:
          - name: PORT
            value: {{ $api.port | quote }}
          - name: EVENT_SOURCE
            value: cloudevents
          - name: PATH_PREFIX
            value: {{ $api.pathPrefix }}
          - name: TIMEZONE
            value: {{ $.Values.timezone }}
          - name: PG_USER
            value: {{ $.Values.postgresql.postgresqlUsername }}
          - name: PG_NAME
            value: {{ $.Values.postgresql.postgresqlDatabase }}
          - name: PG_PREFIX
            value: reports_
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: pg-pass
                key: postgresql-password
          - name: PG_PORT
            value: {{ $.Values.postgresql.port | quote }}
          - name: PG_HOST
            {{- if $.Values.postgresql.internal }}
            value: mds-postgresql.{{ $.Release.Namespace }}.svc.cluster.local
            {{- else }}
            value: {{ $.Values.postgresql.host }}
            {{- end }}
          - name: PG_HOST_READER
            {{- if $.Values.postgresql.internal }}
            value: mds-postgresql.{{ $.Release.Namespace }}.svc.cluster.local
            {{- else }}
            {{- if $.Values.postgresql.hostReader }}
            value: {{ $.Values.postgresql.hostReader }}
            {{- else }}
            value: {{ $.Values.postgresql.host }}
            {{- end }}
            {{- end }}
          {{- if $api.migration }}
          - name: PG_MIGRATIONS
            value: {{ $api.migration | quote }}
          {{- end }}
          - name: REDIS_HOST
            {{- if $.Values.redis.internal }}
            value: mds-redis-master.{{ $.Release.Namespace }}.svc.cluster.local
            {{- else }}
            value: {{ $.Values.redis.host }}
            {{- end }}
          - name: REDIS_PORT
            value: {{ $.Values.redis.port | quote }}
          - name: CE_NAME
            value: {{ $key }}
          - name: SINK
            value: http://default-broker.{{ $.Release.Namespace }}.svc.cluster.local
          {{- end }}
          {{- if $api.env }}
{{ toYaml $api.env | indent 10 }}
          {{- end }}
{{- end }}
{{- end }}
{{- if $.Values.pgPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-pass
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  postgresql-password: {{ $.Values.pgPass | b64enc }}
{{- end}}
