{{- range $api := .Values.apis }}
{{- if $api.jwtAudience }}
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: {{ $api.name }}-auth
  namespace: {{ $.Values.namespace }}
spec:
  targets:
  - name: {{ $api.name }}
  peers:
  - mtls:
      mode: PERMISSIVE
  origins:
  - jwt:
      audiences:
      - {{ $api.jwtAudience | quote }}
      issuer: {{ $.Values.jwt.issuer | quote }}
      jwksUri: {{ printf "%s.well-known/jwks.json" $.Values.jwt.issuer }}
      trigger_rules:
      - excluded_paths:
        - exact: {{ $api.pathPrefix }}/health
        - exact: /health
  principalBinding: USE_ORIGIN
{{- end }}
{{- end }}
