apiVersion: v1
appVersion: 6.5.2
description: Grafana is an open source, feature rich metrics dashboard and graph editor
  for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.
engine: gotpl
home: https://grafana.com/
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analitics
- monitoring
- metrics
- logs
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: grafana
sources:
- https://github.com/bitnami/bitnami-docker-grafana
version: 1.2.0
