{{- range $api := .Values.apis }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $api.name }}-route
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - mds-gateway
  http:
  - match:
    - uri:
        prefix: {{ $api.pathPrefix }}
    route:
    - destination:
        port:
          number: {{ $api.port }}
        host: {{ $api.name }}.{{ $.Values.namespace}}.svc.cluster.local
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - PUT
      - POST
      allowCredentials: false
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "10m"
---
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mds-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  {{- if .Values.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
  {{- else }}
  - port:
      number: 80
      name: http
      protocol: HTTP
  {{- end }}
    hosts:
    - "*"
