dependencies:
  - name: fluent-bit
    alias: fluentbit
    version: 2.7.0
    repository: alias:stable
    condition: fluentbit.enabled
  - name: elasticsearch
    alias: elasticsearch
    version: 7.3.2
    repository: alias:elastic
    condition: elasticsearch.enabled
  - name: kibana
    alias: kibana
    version: 7.3.2
    repository: alias:elastic
    condition: kibana.enabled
